Emmanuel Steve details
shrutikapoor08/talent-for-hire pull request #118
Opened 2021-02-20 03:59 UTC by talk2coded

Hello ! I just added my details, I hope to I'm hired soon.

2021-03-05 21:19 UTC, shrutikapoor08 requested changes
Hey Emmanuel! Looks like formatting is off. Can you enter details within `||` and in the correct section of Nigeria.

2021-03-05 21:46 UTC, talk2coded commented
I’ve updated it 
Sorry about that 

Sent from my iPhone

> On Mar 5, 2021, at 10:19 PM, Shruti Kapoor <notifications@github.com> wrote:
> 
> @shrutikapoor08 requested changes on this pull request.
> 
> Hey Emmanuel! Looks like formatting is off. Can you enter details within || and in the correct section of Nigeria.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-08 06:48 UTC, shrutikapoor08 commented on README.MD
> +|  |  |  |  |  |  |
can you remove this line?

2021-03-08 08:01 UTC, talk2coded commented
Done 

Sent from my iPhone

> On Mar 8, 2021, at 7:48 AM, Shruti Kapoor <notifications@github.com> wrote:
> 
> @shrutikapoor08 commented on this pull request.
> 
> In README.MD:
> 
> > @@ -29,6 +29,8 @@ Country:
>  - [China](#China)
>  - [Sri Lanka](#Sri-Lanka)
>  - [Nigeria](#Nigeria)
> +|  |  |  |  |  |  |
> can you remove this line?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-09 01:29 UTC, shrutikapoor08 approved these changes

2021-03-09 01:29 UTC, merged